# Generated by Django 2.2.8 on 2020-10-28 19:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateField(auto_created=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('content', models.TextField(max_length=400)),
                ('link', models.URLField(max_length=100)),
                ('published', models.BooleanField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
