# Generated by Django 2.2.8 on 2020-10-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorials',
            new_name='Tutorial',
        ),
    ]
